#Checking stuff

In [51]:
import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/ML/Football/matches.csv')
df.head()

,Unnamed: 0,date,time,comp,round,day,venue,result,gf,ga,...,match report,notes,sh,sot,dist,fk,pk,pkatt,season,team
0,1,2021-08-15,16:30,Premier League,Matchweek 1,Sun,Away,L,0.0,1.0,...,Match Report,NaN,18.0,4.0,16.9,1.0,0.0,0.0,2022,Manchester City
1,2,2021-08-21,15:00,Premier League,Matchweek 2,Sat,Home,W,5.0,0.0,...,Match Report,NaN,16.0,4.0,17.3,1.0,0.0,0.0,2022,Manchester City
2,3,2021-08-28,12:30,Premier League,Matchweek 3,Sat,Home,W,5.0,0.0,...,Match Report,NaN,25.0,10.0,14.3,0.0,0.0,0.0,2022,Manchester City
3,4,2021-09-11,15:00,Premier League,Matchweek 4,Sat,Away,W,1.0,0.0,...,Match Report,NaN,25.0,8.0,14.0,0.0,0.0,0.0,2022,Manchester City
4,6,2021-09-18,15:00,Premier League,Matchweek 5,Sat,Home,D,0.0,0.0,...,Match Report,NaN,16.0,1.0,15.7,1.0,0.0,0.0,2022,Manchester City

In [52]:
df.shape

(1389, 28)

In [53]:
df['team'].value_counts() #count of each occurrence

team
Manchester United           72
West Ham United             72
Newcastle United            72
Brighton and Hove Albion    72
Southampton                 72
Tottenham Hotspur           71
Manchester City             71
Leeds United                71
Wolverhampton Wanderers     71
Arsenal                     71
Crystal Palace              71
Burnley                     71
Chelsea                     70
Aston Villa                 70
Leicester City              70
Everton                     70
West Bromwich Albion        38
Fulham                      38
Liverpool                   38
Sheffield United            38
Brentford                   34
Norwich City                33
Watford                     33
Name: count, dtype: int64

In [54]:
df[df['team']=='Liverpool'] #incomplete data, matches not present of 2022

,Unnamed: 0,date,time,comp,round,day,venue,result,gf,ga,...,match report,notes,sh,sot,dist,fk,pk,pkatt,season,team
705,1,2020-09-12,17:30,Premier League,Matchweek 1,Sat,Home,W,4.0,3.0,...,Match Report,NaN,20.0,4.0,17.0,0.0,2.0,2.0,2021,Liverpool
706,2,2020-09-20,16:30,Premier League,Matchweek 2,Sun,Away,W,2.0,0.0,...,Match Report,NaN,17.0,5.0,17.7,1.0,0.0,0.0,2021,Liverpool
707,4,2020-09-28,20:00,Premier League,Matchweek 3,Mon,Home,W,3.0,1.0,...,Match Report,NaN,21.0,9.0,16.8,0.0,0.0,0.0,2021,Liverpool
708,6,2020-10-04,19:15,Premier League,Matchweek 4,Sun,Away,L,2.0,7.0,...,Match Report,NaN,14.0,8.0,15.8,1.0,0.0,0.0,2021,Liverpool
709,7,2020-10-17,12:30,Premier League,Matchweek 5,Sat,Away,D,2.0,2.0,...,Match Report,NaN,22.0,8.0,15.0,1.0,0.0,0.0,2021,Liverpool
710,9,2020-10-24,20:00,Premier League,Matchweek 6,Sat,Home,W,2.0,1.0,...,Match Report,NaN,17.0,5.0,18.2,1.0,0.0,0.0,2021,Liverpool
711,11,2020-10-31,17:30,Premier League,Matchweek 7,Sat,Home,W,2.0,1.0,...,Match Report,NaN,8.0,2.0,18.6,1.0,1.0,1.0,2021,Liverpool
712,13,2020-11-08,16:30,Premier League,Matchweek 8,Sun,Away,D,1.0,1.0,...,Match Report,NaN,9.0,2.0,21.5,0.0,1.0,1.0,2021,Liverpool
713,14,2020-11-22,19:15,Premier League,Matchweek 9,Sun,Home,W,3.0,0.0,...,Match Report,NaN,24.0,12.0,11.9,0.0,0.0,0.0,2021,Liverpool
714,16,2020-11-28,12:30,Premier League,Matchweek 10,Sat,Away,D,1.0,1.0,...,Match Report,NaN,6.0,2.0,20.9,0.0,0.0,0.0,2021,Liverpool
715,18,2020-12-06,19:15,Premier League,Matchweek 11,Sun,Home,W,4.0,0.0,...,Match Report,NaN,11.0,6.0,16.6,1.0,0.0,0.0,2021,Liverpool
716,20,2020-12-13,16:30,Premier League,Matchweek 12,Sun,Away,D,1.0,1.0,...,Match Report,NaN,11.0,5.0,20.0,1.0,1.0,1.0,2021,Liverpool
717,21,2020-12-16,20:00,Premier League,Matchweek 13,Wed,Home,W,2.0,1.0,...,Match Report,NaN,17.0,11.0,15.5,0.0,0.0,0.0,2021,Liverpool
718,22,2020-12-19,12:30,Premier League,Matchweek 14,Sat,Away,W,7.0,0.0,...,Match Report,NaN,14.0,7.0,13.2,1.0,0.0,0.0,2021,Liverpool
719,23,2020-12-27,16:30,Premier League,Matchweek 15,Sun,Home,D,1.0,1.0,...,Match Report,NaN,17.0,2.0,17.8,2.0,0.0,0.0,2021,Liverpool
720,24,2020-12-30,20:00,Premier League,Matchweek 16,Wed,Away,D,0.0,0.0,...,Match Report,NaN,11.0,4.0,16.7,0.0,0.0,0.0,2021,Liverpool
721,25,2021-01-04,20:00,Premier League,Matchweek 17,Mon,Away,L,0.0,1.0,...,Match Report,NaN,17.0,1.0,14.3,0.0,0.0,0.0,2021,Liverpool
722,27,2021-01-17,16:30,Premier League,Matchweek 19,Sun,Home,D,0.0,0.0,...,Match Report,NaN,17.0,3.0,17.1,0.0,0.0,0.0,2021,Liverpool
723,28,2021-01-21,20:00,Premier League,Matchweek 18,Thu,Home,L,0.0,1.0,...,Match Report,NaN,27.0,6.0,17.3,0.0,0.0,0.0,2021,Liverpool
724,30,2021-01-28,20:00,Premier League,Matchweek 20,Thu,Away,W,3.0,1.0,...,Match Report,NaN,14.0,7.0,14.7,0.0,0.0,0.0,2021,Liverpool
725,31,2021-01-31,16:30,Premier League,Matchweek 21,Sun,Away,W,3.0,1.0,...,Match Report,NaN,14.0,5.0,15.3,0.0,0.0,0.0,2021,Liverpool
726,32,2021-02-03,20:15,Premier League,Matchweek 22,Wed,Home,L,0.0,1.0,...,Match Report,NaN,11.0,0.0,19.9,0.0,0.0,0.0,2021,Liverpool
727,33,2021-02-07,16:30,Premier League,Matchweek 23,Sun,Home,L,1.0,4.0,...,Match Report,NaN,7.0,2.0,17.9,1.0,1.0,1.0,2021,Liverpool
728,34,2021-02-13,12:30,Premier League,Matchweek 24,Sat,Away,L,1.0,3.0,...,Match Report,NaN,15.0,4.0,15.4,2.0,0.0,0.0,2021,Liverpool
729,36,2021-02-20,17:30,Premier League,Matchweek 25,Sat,Home,L,0.0,2.0,...,Match Report,NaN,16.0,6.0,15.9,1.0,0.0,0.0,2021,Liverpool
730,37,2021-02-28,19:15,Premier League,Matchweek 26,Sun,Away,W,2.0,0.0,...,Match Report,NaN,15.0,8.0,14.2,0.0,0.0,0.0,2021,Liverpool
731,38,2021-03-04,20:15,Premier League,Matchweek 29,Thu,Home,L,0.0,1.0,...,Match Report,NaN,7.0,1.0,18.4,0.0,0.0,0.0,2021,Liverpool
732,39,2021-03-07,14:00,Premier League,Matchweek 27,Sun,Home,L,0.0,1.0,...,Match Report,NaN,16.0,3.0,17.0,1.0,0.0,0.0,2021,Liverpool
733,41,2021-03-15,20:00,Premier League,Matchweek 28,Mon,Away,W,1.0,0.0,...,Match Report,NaN,12.0,4.0,15.9,0.0,0.0,0.0,2021,Liverpool
734,42,2021-04-03,20:00,Premier League,Matchweek 30,Sat,Away,W,3.0,0.0,...,Match Report,NaN,16.0,7.0,17.0,0.0,0.0,0.0,2021,Liverpool
735,44,2021-04-10,15:00,Premier League,Matchweek 31,Sat,Home,W,2.0,1.0,...,Match Report,NaN,23.0,8.0,16.7,1.0,0.0,0.0,2021,Liverpool
736,46,2021-04-19,20:00,Premier League,Matchweek 32,Mon,Away,D,1.0,1.0,...,Match Report,NaN,17.0,7.0,15.7,0.0,0.0,0.0,2021,Liverpool
737,47,2021-04-24,12:30,Premier League,Matchweek 33,Sat,Home,D,1.0,1.0,...,Match Report,NaN,21.0,9.0,17.0,1.0,0.0,0.0,2021,Liverpool
738,48,2021-05-08,20:15,Premier League,Matchweek 35,Sat,Home,W,2.0,0.0,...,Match Report,NaN,14.0,6.0,12.4,0.0,0.0,0.0,2021,Liverpool
739,49,2021-05-13,20:15,Premier League,Matchweek 34,Thu,Away,W,4.0,2.0,...,Match Report,NaN,17.0,8.0,14.9,0.0,0.0,0.0,2021,Liverpool
740,50,2021-05-16,16:30,Premier League,Matchweek 36,Sun,Away,W,2.0,1.0,...,Match Report,NaN,26.0,6.0,16.9,1.0,0.0,0.0,2021,Liverpool
741,51,2021-05-19,20:15,Premier League,Matchweek 37,Wed,Away,W,3.0,0.0,...,Match Report,NaN,20.0,3.0,15.5,1.0,0.0,0.0,2021,Liverpool
742,52,2021-05-23,16:00,Premier League,Matchweek 38,Sun,Home,W,2.0,0.0,...,Match Report,NaN,19.0,5.0,14.2,1.0,0.0,0.0,2021,Liverpool

In [55]:
df['round'].value_counts() #unequal matches because of scraping

round
Matchweek 1     39
Matchweek 2     39
Matchweek 3     39
Matchweek 4     39
Matchweek 5     39
Matchweek 6     39
Matchweek 7     39
Matchweek 8     39
Matchweek 9     39
Matchweek 10    39
Matchweek 11    39
Matchweek 12    39
Matchweek 13    39
Matchweek 14    39
Matchweek 15    39
Matchweek 16    39
Matchweek 17    39
Matchweek 19    39
Matchweek 20    39
Matchweek 25    39
Matchweek 24    39
Matchweek 23    39
Matchweek 34    39
Matchweek 29    39
Matchweek 31    39
Matchweek 26    39
Matchweek 28    39
Matchweek 32    39
Matchweek 18    37
Matchweek 21    37
Matchweek 22    37
Matchweek 27    37
Matchweek 30    37
Matchweek 33    32
Matchweek 35    20
Matchweek 36    20
Matchweek 37    20
Matchweek 38    20
Name: count, dtype: int64

In [56]:
#df.dtypes
#df['date'].dtype  #o - object
df['date'] = pd.to_datetime(df['date'])
df['date'].dtype
df.dtypes

Unnamed: 0               int64
date            datetime64[ns]
time                    object
comp                    object
round                   object
day                     object
venue                   object
result                  object
gf                     float64
ga                     float64
opponent                object
xg                     float64
xga                    float64
poss                   float64
attendance             float64
captain                 object
formation               object
referee                 object
match report            object
notes                  float64
sh                     float64
sot                    float64
dist                   float64
fk                     float64
pk                     float64
pkatt                  float64
season                   int64
team                    object
dtype: object

#predictor 1 - Venue code

In [57]:
df['venue']

0       Away
1       Home
2       Home
3       Away
4       Home
        ...
1384    Away
1385    Home
1386    Away
1387    Away
1388    Home
Name: venue, Length: 1389, dtype: object

In [58]:
df['venue_code'] = df['venue'].astype('category').cat.codes

In [59]:
df['opponent_code'] = df['opponent'].astype('category').cat.codes

In [60]:
df['hour'] = df['time'].str.replace(":.+", "", regex=True).astype('int')

In [61]:
df['day_code'] = df['date'].dt.dayofweek

In [62]:
df['target'] = (df['result']=='W').astype('int')

In [63]:
df

,Unnamed: 0,date,time,comp,round,day,venue,result,gf,ga,...,fk,pk,pkatt,season,team,venue_code,opponent_code,hour,day_code,target
0,1,2021-08-15,16:30,Premier League,Matchweek 1,Sun,Away,L,0.0,1.0,...,1.0,0.0,0.0,2022,Manchester City,0,18,16,6,0
1,2,2021-08-21,15:00,Premier League,Matchweek 2,Sat,Home,W,5.0,0.0,...,1.0,0.0,0.0,2022,Manchester City,1,15,15,5,1
2,3,2021-08-28,12:30,Premier League,Matchweek 3,Sat,Home,W,5.0,0.0,...,0.0,0.0,0.0,2022,Manchester City,1,0,12,5,1
3,4,2021-09-11,15:00,Premier League,Matchweek 4,Sat,Away,W,1.0,0.0,...,0.0,0.0,0.0,2022,Manchester City,0,10,15,5,1
4,6,2021-09-18,15:00,Premier League,Matchweek 5,Sat,Home,D,0.0,0.0,...,1.0,0.0,0.0,2022,Manchester City,1,17,15,5,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1384,38,2021-05-02,19:15,Premier League,Matchweek 34,Sun,Away,L,0.0,4.0,...,0.0,0.0,0.0,2021,Sheffield United,0,18,19,6,0
1385,39,2021-05-08,15:00,Premier League,Matchweek 35,Sat,Home,L,0.0,2.0,...,1.0,0.0,0.0,2021,Sheffield United,1,6,15,5,0
1386,40,2021-05-16,19:00,Premier League,Matchweek 36,Sun,Away,W,1.0,0.0,...,0.0,0.0,0.0,2021,Sheffield United,0,7,19,6,1
1387,41,2021-05-19,18:00,Premier League,Matchweek 37,Wed,Away,L,0.0,1.0,...,1.0,0.0,0.0,2021,Sheffield United,0,14,18,2,0
1388,42,2021-05-23,16:00,Premier League,Matchweek 38,Sun,Home,W,1.0,0.0,...,0.0,0.0,0.0,2021,Sheffield United,1,4,16,6,1

In [64]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators=50, min_samples_split=10, random_state=1)

In [65]:
train = df[df['date'] < '2022-01-01']
test = df[df['date'] >= '2022-01-01']

In [66]:
predictors = ['venue_code', 'opponent_code', 'hour', 'day_code']

In [67]:
rf.fit(train[predictors], train['target'])

RandomForestClassifier(min_samples_split=10, n_estimators=50, random_state=1)

In [68]:
pred = rf.predict(test[predictors])

In [69]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(test['target'], pred)
accuracy

0.6134751773049646

In [70]:
from sklearn.metrics import precision_score
precision = precision_score(test['target'], pred)
precision

0.48333333333333334

In [71]:
combined = pd.DataFrame(dict(actual=test['target'], predicted=pred))
combined.head()

    actual  predicted
20       1          0
21       1          0
22       0          0
23       1          0
24       1          1

In [72]:
pd.crosstab(index=combined['actual'], columns=combined['predicted'])

predicted    0   1
actual
0          144  31
1           78  29

#rolling everages

In [73]:
grouped_matches = df.groupby('team')
group = grouped_matches.get_group('Manchester City')
group

,Unnamed: 0,date,time,comp,round,day,venue,result,gf,ga,...,fk,pk,pkatt,season,team,venue_code,opponent_code,hour,day_code,target
0,1,2021-08-15,16:30,Premier League,Matchweek 1,Sun,Away,L,0.0,1.0,...,1.0,0.0,0.0,2022,Manchester City,0,18,16,6,0
1,2,2021-08-21,15:00,Premier League,Matchweek 2,Sat,Home,W,5.0,0.0,...,1.0,0.0,0.0,2022,Manchester City,1,15,15,5,1
2,3,2021-08-28,12:30,Premier League,Matchweek 3,Sat,Home,W,5.0,0.0,...,0.0,0.0,0.0,2022,Manchester City,1,0,12,5,1
3,4,2021-09-11,15:00,Premier League,Matchweek 4,Sat,Away,W,1.0,0.0,...,0.0,0.0,0.0,2022,Manchester City,0,10,15,5,1
4,6,2021-09-18,15:00,Premier League,Matchweek 5,Sat,Home,D,0.0,0.0,...,1.0,0.0,0.0,2022,Manchester City,1,17,15,5,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
662,54,2021-05-01,12:30,Premier League,Matchweek 34,Sat,Away,W,2.0,0.0,...,1.0,0.0,0.0,2021,Manchester City,0,6,12,5,1
663,56,2021-05-08,17:30,Premier League,Matchweek 35,Sat,Home,L,1.0,2.0,...,0.0,0.0,1.0,2021,Manchester City,1,5,17,5,0
664,57,2021-05-14,20:00,Premier League,Matchweek 36,Fri,Away,W,4.0,3.0,...,1.0,0.0,0.0,2021,Manchester City,0,14,20,4,1
665,58,2021-05-18,19:00,Premier League,Matchweek 37,Tue,Away,L,2.0,3.0,...,1.0,0.0,0.0,2021,Manchester City,0,3,19,1,0
666,59,2021-05-23,16:00,Premier League,Matchweek 38,Sun,Home,W,5.0,0.0,...,0.0,0.0,0.0,2021,Manchester City,1,7,16,6,1

In [74]:
def rolling_averages(group, cols, new_cols):
  group = group.sort_values('date')
  for i, col in enumerate(cols):
    rolling_stats = group[col].rolling(3, closed = 'left').mean()
    group[new_cols[i]] = rolling_stats
  group = group.dropna(subset=new_cols)
  return group

In [75]:
cols = ['gf', 'ga', 'sh', 'sot', 'dist', 'fk', 'pk', 'pkatt']
new_cols = [f'{c}_rolling' for c in cols]
new_cols

['gf_rolling',
 'ga_rolling',
 'sh_rolling',
 'sot_rolling',
 'dist_rolling',
 'fk_rolling',
 'pk_rolling',
 'pkatt_rolling']

In [76]:
rolling_averages(group, cols, new_cols)

,Unnamed: 0,date,time,comp,round,day,venue,result,gf,ga,...,day_code,target,gf_rolling,ga_rolling,sh_rolling,sot_rolling,dist_rolling,fk_rolling,pk_rolling,pkatt_rolling
632,5,2020-10-17,17:30,Premier League,Matchweek 5,Sat,Home,W,1.0,0.0,...,5,1,2.000000,2.333333,17.333333,4.666667,18.900000,1.333333,0.333333,0.333333
633,7,2020-10-24,12:30,Premier League,Matchweek 6,Sat,Away,D,1.0,1.0,...,5,0,1.333333,2.000000,17.333333,3.666667,17.733333,0.666667,0.000000,0.000000
634,9,2020-10-31,12:30,Premier League,Matchweek 7,Sat,Away,W,1.0,0.0,...,5,1,1.000000,0.666667,16.666667,4.333333,18.233333,0.666667,0.000000,0.000000
635,11,2020-11-08,16:30,Premier League,Matchweek 8,Sun,Home,D,1.0,1.0,...,6,0,1.000000,0.333333,14.333333,6.666667,18.466667,1.000000,0.000000,0.000000
636,12,2020-11-21,17:30,Premier League,Matchweek 9,Sat,Away,L,0.0,2.0,...,5,0,1.000000,0.666667,12.000000,5.666667,19.366667,1.000000,0.000000,0.333333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28,42,2022-03-14,20:00,Premier League,Matchweek 29,Mon,Away,D,0.0,0.0,...,0,0,2.333333,1.333333,19.000000,7.000000,15.366667,0.333333,0.333333,0.333333
29,44,2022-04-02,15:00,Premier League,Matchweek 31,Sat,Away,W,2.0,0.0,...,5,1,1.666667,0.333333,18.333333,7.333333,16.000000,0.333333,0.000000,0.000000
30,46,2022-04-10,16:30,Premier League,Matchweek 32,Sun,Home,D,2.0,2.0,...,6,0,2.000000,0.333333,20.000000,6.666667,16.133333,0.333333,0.000000,0.000000
31,49,2022-04-20,20:00,Premier League,Matchweek 30,Wed,Home,W,3.0,0.0,...,2,1,1.333333,0.666667,15.666667,4.666667,16.700000,0.333333,0.000000,0.000000
32,50,2022-04-23,15:00,Premier League,Matchweek 34,Sat,Home,W,5.0,1.0,...,5,1,2.333333,0.666667,15.333333,5.000000,17.200000,0.333333,0.000000,0.000000

In [77]:
matches_rolling = df.groupby('team').apply(lambda x: rolling_averages(x, cols, new_cols))
matches_rolling = matches_rolling.droplevel('team')
matches_rolling = matches_rolling.drop(df.columns[0], axis=1)
matches_rolling

/tmp/ipython-input-2468780166.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  matches_rolling = df.groupby('team').apply(lambda x: rolling_averages(x, cols, new_cols))

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,day_code,target,gf_rolling,ga_rolling,sh_rolling,sot_rolling,dist_rolling,fk_rolling,pk_rolling,pkatt_rolling
898,2020-10-04,14:00,Premier League,Matchweek 4,Sun,Home,W,2.0,1.0,Sheffield Utd,...,6,1,2.000000,1.333333,7.666667,3.666667,14.733333,0.666667,0.000000,0.000000
899,2020-10-17,17:30,Premier League,Matchweek 5,Sat,Away,L,0.0,1.0,Manchester City,...,5,0,1.666667,1.666667,5.333333,3.666667,15.766667,0.000000,0.000000,0.000000
900,2020-10-25,19:15,Premier League,Matchweek 6,Sun,Home,L,0.0,1.0,Leicester City,...,6,0,1.000000,1.666667,7.000000,3.666667,16.733333,0.666667,0.000000,0.000000
901,2020-11-01,16:30,Premier League,Matchweek 7,Sun,Away,W,1.0,0.0,Manchester Utd,...,6,1,0.666667,1.000000,9.666667,4.000000,16.033333,1.000000,0.000000,0.000000
902,2020-11-08,19:15,Premier League,Matchweek 8,Sun,Home,L,0.0,3.0,Aston Villa,...,6,0,0.333333,0.666667,9.666667,2.666667,18.033333,1.000000,0.333333,0.333333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
227,2022-03-13,14:00,Premier League,Matchweek 29,Sun,Away,W,1.0,0.0,Everton,...,6,1,1.333333,1.000000,12.333333,3.666667,19.300000,0.000000,0.000000,0.000000
228,2022-03-18,20:00,Premier League,Matchweek 30,Fri,Home,L,2.0,3.0,Leeds United,...,4,0,1.666667,0.666667,12.333333,4.333333,19.600000,0.000000,0.000000,0.000000
229,2022-04-02,15:00,Premier League,Matchweek 31,Sat,Home,W,2.0,1.0,Aston Villa,...,5,1,2.333333,1.000000,13.000000,5.333333,19.833333,0.000000,0.000000,0.000000
230,2022-04-08,20:00,Premier League,Matchweek 32,Fri,Away,L,0.0,1.0,Newcastle Utd,...,4,0,1.666667,1.333333,13.000000,5.000000,18.533333,0.000000,0.000000,0.000000
231,2022-04-24,14:00,Premier League,Matchweek 34,Sun,Away,L,0.0,1.0,Burnley,...,6,0,1.333333,1.666667,10.000000,4.666667,17.633333,0.000000,0.000000,0.000000

In [78]:
matches_rolling.index = range(matches_rolling.shape[0])
matches_rolling

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,day_code,target,gf_rolling,ga_rolling,sh_rolling,sot_rolling,dist_rolling,fk_rolling,pk_rolling,pkatt_rolling
0,2020-10-04,14:00,Premier League,Matchweek 4,Sun,Home,W,2.0,1.0,Sheffield Utd,...,6,1,2.000000,1.333333,7.666667,3.666667,14.733333,0.666667,0.000000,0.000000
1,2020-10-17,17:30,Premier League,Matchweek 5,Sat,Away,L,0.0,1.0,Manchester City,...,5,0,1.666667,1.666667,5.333333,3.666667,15.766667,0.000000,0.000000,0.000000
2,2020-10-25,19:15,Premier League,Matchweek 6,Sun,Home,L,0.0,1.0,Leicester City,...,6,0,1.000000,1.666667,7.000000,3.666667,16.733333,0.666667,0.000000,0.000000
3,2020-11-01,16:30,Premier League,Matchweek 7,Sun,Away,W,1.0,0.0,Manchester Utd,...,6,1,0.666667,1.000000,9.666667,4.000000,16.033333,1.000000,0.000000,0.000000
4,2020-11-08,19:15,Premier League,Matchweek 8,Sun,Home,L,0.0,3.0,Aston Villa,...,6,0,0.333333,0.666667,9.666667,2.666667,18.033333,1.000000,0.333333,0.333333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1312,2022-03-13,14:00,Premier League,Matchweek 29,Sun,Away,W,1.0,0.0,Everton,...,6,1,1.333333,1.000000,12.333333,3.666667,19.300000,0.000000,0.000000,0.000000
1313,2022-03-18,20:00,Premier League,Matchweek 30,Fri,Home,L,2.0,3.0,Leeds United,...,4,0,1.666667,0.666667,12.333333,4.333333,19.600000,0.000000,0.000000,0.000000
1314,2022-04-02,15:00,Premier League,Matchweek 31,Sat,Home,W,2.0,1.0,Aston Villa,...,5,1,2.333333,1.000000,13.000000,5.333333,19.833333,0.000000,0.000000,0.000000
1315,2022-04-08,20:00,Premier League,Matchweek 32,Fri,Away,L,0.0,1.0,Newcastle Utd,...,4,0,1.666667,1.333333,13.000000,5.000000,18.533333,0.000000,0.000000,0.000000
1316,2022-04-24,14:00,Premier League,Matchweek 34,Sun,Away,L,0.0,1.0,Burnley,...,6,0,1.333333,1.666667,10.000000,4.666667,17.633333,0.000000,0.000000,0.000000

In [79]:
def make_prediction(data, predictors):
  train = matches_rolling[matches_rolling['date'] < '2022-01-01']
  test = matches_rolling[matches_rolling['date'] >= '2022-01-01']
  rf.fit(train[predictors], train['target'])
  pred = rf.predict(test[predictors])
  combined = pd.DataFrame(dict(actual=test['target'], predicted=pred), index=test.index)
  precision = precision_score(test['target'], pred)
  return combined, precision

In [80]:
combined, precision = make_prediction(matches_rolling, predictors + new_cols)

In [81]:
print(precision)
combined.head()

0.625

    actual  predicted
54       0          0
55       0          0
56       1          0
57       1          0
58       1          1

In [82]:
combined = combined.merge(matches_rolling[['date', 'team', 'opponent', 'result']], left_index=True, right_index=True)
combined

,actual,predicted,date,team,opponent,result
54,0,0,2022-01-01,Arsenal,Manchester City,L
55,0,0,2022-01-23,Arsenal,Burnley,D
56,1,0,2022-02-10,Arsenal,Wolves,W
57,1,0,2022-02-19,Arsenal,Brentford,W
58,1,1,2022-02-24,Arsenal,Wolves,W
...,...,...,...,...,...,...
1312,1,0,2022-03-13,Wolverhampton Wanderers,Everton,W
1313,0,0,2022-03-18,Wolverhampton Wanderers,Leeds United,L
1314,1,0,2022-04-02,Wolverhampton Wanderers,Aston Villa,W
1315,0,0,2022-04-08,Wolverhampton Wanderers,Newcastle Utd,L
1316,0,0,2022-04-24,Wolverhampton Wanderers,Burnley,L

In [83]:
class MissingDict(dict):
  __missing__= lambda self, key: key

map_values = {"Brighton and Hove Albion": "Brighton",
              "Manchester United": "Manchester Utd",
              "Newcastle United": "Newcastle Utd",
              "Tottenham Hotspur": "Tottenham",
              "West Ham United": "West Ham",
              "Wolverhampton Wanderers": "Wolves"}

mapping = MissingDict(map_values)

In [84]:
mapping['Brighton and Hove Albion']

'Brighton'

In [86]:
combined['new_team'] = combined['team'].map(mapping)
combined

,actual,predicted,date,team,opponent,result,new_team
54,0,0,2022-01-01,Arsenal,Manchester City,L,Arsenal
55,0,0,2022-01-23,Arsenal,Burnley,D,Arsenal
56,1,0,2022-02-10,Arsenal,Wolves,W,Arsenal
57,1,0,2022-02-19,Arsenal,Brentford,W,Arsenal
58,1,1,2022-02-24,Arsenal,Wolves,W,Arsenal
...,...,...,...,...,...,...,...
1312,1,0,2022-03-13,Wolverhampton Wanderers,Everton,W,Wolves
1313,0,0,2022-03-18,Wolverhampton Wanderers,Leeds United,L,Wolves
1314,1,0,2022-04-02,Wolverhampton Wanderers,Aston Villa,W,Wolves
1315,0,0,2022-04-08,Wolverhampton Wanderers,Newcastle Utd,L,Wolves
1316,0,0,2022-04-24,Wolverhampton Wanderers,Burnley,L,Wolves

In [87]:
merged = combined.merge(combined, left_on=['date', 'new_team'], right_on=['date', 'opponent'])
merged

,actual_x,predicted_x,date,team_x,opponent_x,result_x,new_team_x,actual_y,predicted_y,team_y,opponent_y,result_y,new_team_y
0,0,0,2022-01-01,Arsenal,Manchester City,L,Arsenal,1,0,Manchester City,Arsenal,W,Manchester City
1,0,0,2022-01-23,Arsenal,Burnley,D,Arsenal,0,0,Burnley,Arsenal,D,Burnley
2,1,0,2022-02-10,Arsenal,Wolves,W,Arsenal,0,0,Wolverhampton Wanderers,Arsenal,L,Wolves
3,1,0,2022-02-19,Arsenal,Brentford,W,Arsenal,0,0,Brentford,Arsenal,L,Brentford
4,1,1,2022-02-24,Arsenal,Wolves,W,Arsenal,0,0,Wolverhampton Wanderers,Arsenal,L,Wolves
...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,1,0,2022-03-13,Wolverhampton Wanderers,Everton,W,Wolves,0,0,Everton,Wolves,L,Everton
264,0,0,2022-03-18,Wolverhampton Wanderers,Leeds United,L,Wolves,1,0,Leeds United,Wolves,W,Leeds United
265,1,0,2022-04-02,Wolverhampton Wanderers,Aston Villa,W,Wolves,0,0,Aston Villa,Wolves,L,Aston Villa
266,0,0,2022-04-08,Wolverhampton Wanderers,Newcastle Utd,L,Wolves,1,0,Newcastle United,Wolves,W,Newcastle Utd
267,0,0,2022-04-24,Wolverhampton Wanderers,Burnley,L,Wolves,1,0,Burnley,Wolves,W,Burnley

In [93]:
merged[(merged['predicted_x']==1) & (merged['predicted_y']==0)]['actual_x'].value_counts()

actual_x
1    27
0    13
Name: count, dtype: int64

In [95]:
print("accuracy: ", 27/40) # improved a little

accuracy:  0.675